"""SystemConfig repository interface."""
from __future__ import annotations

from typing import Protocol


class SystemConfigRepository(Protocol):
    def get(self, key: str) -> str | None: ...
    def set(self, key: str, value: str, *, encrypted: bool = False) -> None: ...
    def delete(self, key: str) -> None: ...
    def get_all(self) -> dict[str, str]: ...
    def get_by_prefix(self, prefix: str) -> dict[str, str]: ...
